### ISSUE TITLE
Update PAT information in regards to new fine-grained PATs

### ISSUE THREAD

**Issue by gunnarmorling** [jreleaser/jreleaser.github.io#47]
I wanted to send a PR for adding info about the new GH PATs (see https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/), but I couldn't find the _token.adoc_ file which seems to contain those contents? Happy to send a PR if you can point me into the right direction, @aalmiray.

**Comment by aalmiray** [comment]
I think the file you're looking for is this one https://github.com/jreleaser/jreleaser.github.io/blob/main/docs/modules/reference/partials/packagers/token.adoc

We've split the documentation into actual pages and "partials". The token description is found on a partial and that's why you didn't find it directly as I believe Antora doesn't have the capability to direct to partials but only to pages via its' Edit this page" function.

**Comment by gunnarmorling** [comment]
Sweet; PR is at https://github.com/jreleaser/jreleaser.github.io/pull/48
